dist: trusty
language: php
sudo: required

php:
  - '7.2'

branches:
  only:
    - dev

addons:
  hosts:
  - dbp.test

before_install:
  - mysql -e 'CREATE DATABASE dbp;'
  - mysql -e 'CREATE DATABASE dbp_users;'
  - mysql -e 'CREATE DATABASE sophia;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - npm install
  - php artisan key:generate
  - php artisan migrate

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="4"