dist: trusty
language: php

php:
  - 7.2

branches:
  only:
    - dev

addons:
  hosts:
  - dbp.test

before_install:
  - mysql -e 'CREATE DATABASE dbp;'
  - mysql -e 'CREATE DATABASE dbp_users;'

before_script:
  - phpenv config-add travis.php.ini
  - cp .env.travis .env
  - composer self-update
  - rm -rf vendor
  - composer install
  - npm install
  - php artisan key:generate
  - php artisan migrate --seed
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ $(phpenv version-name) = "7.2" ]; then ./cc-test-reporter before-build; fi

script:
  - phpunit --group=travis

after:
  - if [ $(phpenv version-name) = "7.2" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="4"
  global:
    - CC_TEST_REPORTER_ID=86a09970f02b3f841b263963099a65adf9bf9e85ea72db88a1d5f5ac003d01f2
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)