language: php

php:
  - 7.2

branches:
  only:
    - master
    - dev

addons:
  hosts:
  - dbp.test

before_install:
  - mysql -e 'CREATE DATABASE dbp;'
  - mysql -e 'CREATE DATABASE dbp_users;'

before_script:
  - phpenv config-add travis.php.ini
  - cp .env.travis .env
  - composer install
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - phpunit --group=travis

services:
  - mysql

env:
  - TRAVIS_NODE_VERSION="4"
