version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-stretch-node-browsers
      - image: circleci/mysql:5.7-ram

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          - v1-dependencies-

      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      - run: cp .env.testing .env
      - run: php artisan key:generate
      - run: php artisan migrate  --seed
      #- run: ./vendor/bin/phpunit
